2025-05-12 04:22:53,552 | INFO | üìÑ Starting processing file: 2025 - 01 - 03- Night Audit Packet.pdf
2025-05-12 04:22:54,111 | INFO | üìÑ Starting processing file: 2025 - 01 - 05- Night Audit Packet.pdf
2025-05-12 04:22:54,147 | INFO | üìÑ Starting processing file: 2025 - 01 - 08- Night Audit Packet.pdf
2025-05-12 04:22:54,252 | INFO | üìÑ Starting processing file: 2025 - 01 - 09- Night Audit Packet.pdf
2025-05-12 04:22:54,254 | INFO | ‚è≠Ô∏è Skipping already processed file in worker: 2025 - 01 - 06- Night Audit Packet.pdf
2025-05-12 04:22:54,266 | INFO | üìÑ Starting processing file: 2025 - 01 - 10- Night Audit Packet.pdf
2025-05-12 04:22:54,278 | INFO | üìÑ Starting processing file: 2025 - 01 - 07- Night Audit Packet.pdf
2025-05-12 04:22:55,044 | INFO | üìß Email sent successfully.
2025-05-12 04:22:55,048 | INFO | üìÑ Starting processing file: 2025 - 01 - 13- Night Audit Packet.pdf
2025-05-12 04:25:34,936 | INFO | ‚úÖ Processed A/R Aging
2025-05-12 04:25:37,742 | INFO | ‚úÖ Processed Transaction Closeout
2025-05-12 04:25:38,372 | INFO | ‚úÖ Processed In-House List
2025-05-12 04:25:38,521 | INFO | ‚úÖ Processed room_statistics
2025-05-12 04:25:38,617 | INFO | ‚úÖ Processed performance_statistics
2025-05-12 04:25:38,659 | INFO | ‚úÖ Processed guest_statistics
2025-05-12 04:25:38,734 | INFO | ‚úÖ Processed Ledger Activity
2025-05-12 04:25:39,359 | INFO | ‚úÖ Processed A/R Aging
2025-05-12 04:25:39,669 | INFO | ‚úÖ Processed Transaction Closeout
2025-05-12 04:25:39,899 | INFO | ‚úÖ Processed In-House List
2025-05-12 04:25:39,981 | INFO | ‚úÖ Processed room_statistics
2025-05-12 04:25:40,016 | INFO | ‚úÖ Processed performance_statistics
2025-05-12 04:25:40,047 | INFO | ‚úÖ Processed guest_statistics
2025-05-12 04:25:40,104 | INFO | ‚úÖ Processed Ledger Activity
2025-05-12 04:26:23,749 | ERROR | ‚ùå A/R Aging extraction failed: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '169773-FL453-2025-01-06' for key 'ar_aging.PRIMARY'
[SQL: INSERT INTO ar_aging (account, guest_name, current, days_30, days_60, days_90, days_120, credits, balance, limit_amount, property_code, user, report_date, source_file, load_timestamp) VALUES (%(account)s, %(guest_name)s, %(current)s, %(days_30)s, %(days_60)s, %(days_90)s, %(days_120)s, %(credits)s, %(balance)s, %(limit_amount)s, %(property_code)s, %(user)s, %(report_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'account': '169773', 'guest_name': 'CHOICE PRIVILEGES A/R ACCT# 106', 'current': 500.0, 'days_30': 400.0, 'days_60': 250.66, 'days_90': 0.0, 'days_120': 71698.11, 'credits': 0.0, 'balance': 72848.77, 'limit_amount': 5000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '447128', 'guest_name': 'CORPORATE LODGING CONSULTANTS', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 130722.73, 'credits': -6.26, 'balance': 130722.73, 'limit_amount': 10000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1262583', 'guest_name': 'NWFL SYMPHONY ORCHESTRA', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 75.47, 'credits': 0.0, 'balance': 75.47, 'limit_amount': 5000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1459824', 'guest_name': 'H20 PRUF, LLC', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 639.18, 'credits': 0.0, 'balance': 639.18, 'limit_amount': 1500.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1526533', 'guest_name': 'DELTA AIRLINES INC.', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 908.93, 'credits': 0.0, 'balance': 908.93, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1530547', 'guest_name': 'Unpaid Folios', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 9485.14, 'credits': 0.0, 'balance': 9485.14, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1557431', 'guest_name': 'HALPERNS SEAFOOD', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 201.4, 'credits': 0.0, 'balance': 201.4, 'limit_amount': 2000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1607500', 'guest_name': 'Thunderbird', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 301.0, 'credits': 0.0, 'balance': 301.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}  ... displaying 10 of 32 total bound parameter sets ...  {'account': '3448722', 'guest_name': 'Niceville Housing Authority', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 516.0, 'credits': 0.0, 'balance': 516.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '3601939', 'guest_name': 'Stuckman Tree Cutting Company', 'current': 0.0, 'days_30': 960.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 0.0, 'credits': 0.0, 'balance': 960.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '169773-FL453-2025-01-06' for key 'ar_aging.PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 85, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 45, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '169773-FL453-2025-01-06' for key 'ar_aging.PRIMARY'
[SQL: INSERT INTO ar_aging (account, guest_name, current, days_30, days_60, days_90, days_120, credits, balance, limit_amount, property_code, user, report_date, source_file, load_timestamp) VALUES (%(account)s, %(guest_name)s, %(current)s, %(days_30)s, %(days_60)s, %(days_90)s, %(days_120)s, %(credits)s, %(balance)s, %(limit_amount)s, %(property_code)s, %(user)s, %(report_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'account': '169773', 'guest_name': 'CHOICE PRIVILEGES A/R ACCT# 106', 'current': 500.0, 'days_30': 400.0, 'days_60': 250.66, 'days_90': 0.0, 'days_120': 71698.11, 'credits': 0.0, 'balance': 72848.77, 'limit_amount': 5000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '447128', 'guest_name': 'CORPORATE LODGING CONSULTANTS', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 130722.73, 'credits': -6.26, 'balance': 130722.73, 'limit_amount': 10000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1262583', 'guest_name': 'NWFL SYMPHONY ORCHESTRA', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 75.47, 'credits': 0.0, 'balance': 75.47, 'limit_amount': 5000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1459824', 'guest_name': 'H20 PRUF, LLC', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 639.18, 'credits': 0.0, 'balance': 639.18, 'limit_amount': 1500.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1526533', 'guest_name': 'DELTA AIRLINES INC.', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 908.93, 'credits': 0.0, 'balance': 908.93, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1530547', 'guest_name': 'Unpaid Folios', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 9485.14, 'credits': 0.0, 'balance': 9485.14, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1557431', 'guest_name': 'HALPERNS SEAFOOD', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 201.4, 'credits': 0.0, 'balance': 201.4, 'limit_amount': 2000.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '1607500', 'guest_name': 'Thunderbird', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 301.0, 'credits': 0.0, 'balance': 301.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}  ... displaying 10 of 32 total bound parameter sets ...  {'account': '3448722', 'guest_name': 'Niceville Housing Authority', 'current': 0.0, 'days_30': 0.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 516.0, 'credits': 0.0, 'balance': 516.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)}, {'account': '3601939', 'guest_name': 'Stuckman Tree Cutting Company', 'current': 0.0, 'days_30': 960.0, 'days_60': 0.0, 'days_90': 0.0, 'days_120': 0.0, 'credits': 0.0, 'balance': 960.0, 'limit_amount': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'report_date': datetime.date(2025, 1, 6), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 18, 220228)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

2025-05-12 04:26:41,729 | INFO | ‚úÖ Processed A/R Aging
2025-05-12 04:26:42,567 | ERROR | ‚ùå Transaction Closeout extraction failed: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'Direct Bill (DB)-FL453-2025-01-05' for key 'transaction_closeout.PRIMARY'
[SQL: INSERT INTO transaction_closeout (description, opening_balance, todays_total, todays_adjustments, todays_net, ptd_totals, ytd_totals, property_code, user, business_date, source_file, load_timestamp) VALUES (%(description)s, %(opening_balance)s, %(todays_total)s, %(todays_adjustments)s, %(todays_net)s, %(ptd_totals)s, %(ytd_totals)s, %(property_code)s, %(user)s, %(business_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'description': 'Direct Bill (DB)', 'opening_balance': -486.8, 'todays_total': -25.0, 'todays_adjustments': 0.0, 'todays_net': -25.0, 'ptd_totals': -511.8, 'ytd_totals': -511.8, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Direct Billing Receivable (DR)', 'opening_balance': 486.8, 'todays_total': 25.0, 'todays_adjustments': 0.0, 'todays_net': 25.0, 'ptd_totals': 511.8, 'ytd_totals': 511.8, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'RECEIVABLE:', 'opening_balance': 0.0, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': 0.0, 'ytd_totals': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Cash (CA)', 'opening_balance': -346.18, 'todays_total': -214.11, 'todays_adjustments': 0.0, 'todays_net': -214.11, 'ptd_totals': -560.29, 'ytd_totals': -560.29, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Total For CASH:', 'opening_balance': -346.18, 'todays_total': -214.11, 'todays_adjustments': 0.0, 'todays_net': -214.11, 'ptd_totals': -560.29, 'ytd_totals': -560.29, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'American Express (AX)', 'opening_balance': -1321.78, 'todays_total': -1948.8, 'todays_adjustments': 0.0, 'todays_net': -1948.8, 'ptd_totals': -3270.58, 'ytd_totals': -3270.58, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Master Card (MC)', 'opening_balance': -823.15, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': -823.15, 'ytd_totals': -823.15, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Visa Payment (VI)', 'opening_balance': -1269.91, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': -1269.91, 'ytd_totals': -1269.91, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}  ... displaying 10 of 14 total bound parameter sets ...  {'description': 'Tourism Tax (T5)', 'opening_balance': 299.92, 'todays_total': 76.69, 'todays_adjustments': 0.0, 'todays_net': 76.69, 'ptd_totals': 376.61, 'ytd_totals': 376.61, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Total For TAX:', 'opening_balance': 719.78, 'todays_total': 184.04, 'todays_adjustments': 0.0, 'todays_net': 184.04, 'ptd_totals': 903.82, 'ytd_totals': 903.82, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Direct Bill (DB)-FL453-2025-01-05' for key 'transaction_closeout.PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 85, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 45, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'Direct Bill (DB)-FL453-2025-01-05' for key 'transaction_closeout.PRIMARY'
[SQL: INSERT INTO transaction_closeout (description, opening_balance, todays_total, todays_adjustments, todays_net, ptd_totals, ytd_totals, property_code, user, business_date, source_file, load_timestamp) VALUES (%(description)s, %(opening_balance)s, %(todays_total)s, %(todays_adjustments)s, %(todays_net)s, %(ptd_totals)s, %(ytd_totals)s, %(property_code)s, %(user)s, %(business_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'description': 'Direct Bill (DB)', 'opening_balance': -486.8, 'todays_total': -25.0, 'todays_adjustments': 0.0, 'todays_net': -25.0, 'ptd_totals': -511.8, 'ytd_totals': -511.8, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Direct Billing Receivable (DR)', 'opening_balance': 486.8, 'todays_total': 25.0, 'todays_adjustments': 0.0, 'todays_net': 25.0, 'ptd_totals': 511.8, 'ytd_totals': 511.8, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'RECEIVABLE:', 'opening_balance': 0.0, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': 0.0, 'ytd_totals': 0.0, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Cash (CA)', 'opening_balance': -346.18, 'todays_total': -214.11, 'todays_adjustments': 0.0, 'todays_net': -214.11, 'ptd_totals': -560.29, 'ytd_totals': -560.29, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Total For CASH:', 'opening_balance': -346.18, 'todays_total': -214.11, 'todays_adjustments': 0.0, 'todays_net': -214.11, 'ptd_totals': -560.29, 'ytd_totals': -560.29, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'American Express (AX)', 'opening_balance': -1321.78, 'todays_total': -1948.8, 'todays_adjustments': 0.0, 'todays_net': -1948.8, 'ptd_totals': -3270.58, 'ytd_totals': -3270.58, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Master Card (MC)', 'opening_balance': -823.15, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': -823.15, 'ytd_totals': -823.15, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Visa Payment (VI)', 'opening_balance': -1269.91, 'todays_total': 0.0, 'todays_adjustments': 0.0, 'todays_net': 0.0, 'ptd_totals': -1269.91, 'ytd_totals': -1269.91, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}  ... displaying 10 of 14 total bound parameter sets ...  {'description': 'Tourism Tax (T5)', 'opening_balance': 299.92, 'todays_total': 76.69, 'todays_adjustments': 0.0, 'todays_net': 76.69, 'ptd_totals': 376.61, 'ytd_totals': 376.61, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)}, {'description': 'Total For TAX:', 'opening_balance': 719.78, 'todays_total': 184.04, 'todays_adjustments': 0.0, 'todays_net': 184.04, 'ptd_totals': 903.82, 'ytd_totals': 903.82, 'property_code': 'FL453', 'user': 'reaga.fl453', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 26, 40, 720253)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

2025-05-12 04:26:51,201 | INFO | ‚úÖ Processed In-House List
2025-05-12 04:26:51,201 | INFO | ‚úÖ Processed Transaction Closeout
2025-05-12 04:26:51,695 | INFO | ‚úÖ Processed In-House List
2025-05-12 04:26:51,771 | INFO | ‚úÖ Processed room_statistics
2025-05-12 04:26:51,814 | INFO | ‚úÖ Processed performance_statistics
2025-05-12 04:26:51,858 | INFO | ‚úÖ Processed guest_statistics
2025-05-12 04:26:51,945 | INFO | ‚úÖ Processed Ledger Activity
2025-05-12 04:27:14,797 | ERROR | ‚ùå room_statistics extraction failed: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '2025-01-05-2025 - 01 - 05- Night Audit Packet.pdf-Total Rooms' for key 'room_statistics.PRIMARY'
[SQL: INSERT INTO room_statistics (metric, today, current_ptd, last_year_ptd, current_ytd, last_ytd, business_date, source_file, load_timestamp) VALUES (%(metric)s, %(today)s, %(current_ptd)s, %(last_year_ptd)s, %(current_ytd)s, %(last_ytd)s, %(business_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'metric': 'Total Rooms', 'today': '111', 'current_ptd': '555', 'last_year_ptd': '555', 'current_ytd': '555', 'last_ytd': '555', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Out Of Order', 'today': '47', 'current_ptd': '224', 'last_year_ptd': '214', 'current_ytd': '224', 'last_ytd': '214', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Rooms Available to Sell', 'today': '64', 'current_ptd': '331', 'last_year_ptd': '341', 'current_ytd': '331', 'last_ytd': '341', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Day Use Rooms', 'today': '0', 'current_ptd': '0', 'last_year_ptd': '0', 'current_ytd': '0', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Stay Over Rooms', 'today': '26', 'current_ptd': '129', 'last_year_ptd': '177', 'current_ytd': '129', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Revenue Rooms', 'today': '26', 'current_ptd': '129', 'last_year_ptd': '177', 'current_ytd': '129', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Comp Rooms', 'today': '5', 'current_ptd': '25', 'last_year_ptd': '0', 'current_ytd': '25', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Non-Revenue Rooms', 'today': '5', 'current_ptd': '25', 'last_year_ptd': '0', 'current_ytd': '25', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Occupied Rooms', 'today': '31', 'current_ptd': '154', 'last_year_ptd': '177', 'current_ytd': '154', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '2025-01-05-2025 - 01 - 05- Night Audit Packet.pdf-Total Rooms' for key 'room_statistics.PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 85, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 45, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 643, in executemany
    return self.execute(stmt)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/cursor.py", line 537, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 872, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/anaconda3/lib/python3.9/site-packages/mysql/connector/connection.py", line 648, in _handle_result
    raise get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '2025-01-05-2025 - 01 - 05- Night Audit Packet.pdf-Total Rooms' for key 'room_statistics.PRIMARY'
[SQL: INSERT INTO room_statistics (metric, today, current_ptd, last_year_ptd, current_ytd, last_ytd, business_date, source_file, load_timestamp) VALUES (%(metric)s, %(today)s, %(current_ptd)s, %(last_year_ptd)s, %(current_ytd)s, %(last_ytd)s, %(business_date)s, %(source_file)s, %(load_timestamp)s)]
[parameters: ({'metric': 'Total Rooms', 'today': '111', 'current_ptd': '555', 'last_year_ptd': '555', 'current_ytd': '555', 'last_ytd': '555', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Out Of Order', 'today': '47', 'current_ptd': '224', 'last_year_ptd': '214', 'current_ytd': '224', 'last_ytd': '214', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Rooms Available to Sell', 'today': '64', 'current_ptd': '331', 'last_year_ptd': '341', 'current_ytd': '331', 'last_ytd': '341', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Day Use Rooms', 'today': '0', 'current_ptd': '0', 'last_year_ptd': '0', 'current_ytd': '0', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Stay Over Rooms', 'today': '26', 'current_ptd': '129', 'last_year_ptd': '177', 'current_ytd': '129', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Revenue Rooms', 'today': '26', 'current_ptd': '129', 'last_year_ptd': '177', 'current_ytd': '129', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Comp Rooms', 'today': '5', 'current_ptd': '25', 'last_year_ptd': '0', 'current_ytd': '25', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Non-Revenue Rooms', 'today': '5', 'current_ptd': '25', 'last_year_ptd': '0', 'current_ytd': '25', 'last_ytd': '0', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)}, {'metric': 'Total Occupied Rooms', 'today': '31', 'current_ptd': '154', 'last_year_ptd': '177', 'current_ytd': '154', 'last_ytd': '177', 'business_date': datetime.date(2025, 1, 5), 'source_file': '2025 - 01 - 05- Night Audit Packet.pdf', 'load_timestamp': datetime.datetime(2025, 5, 12, 4, 27, 10, 387968)})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

